# Generated by Django 4.2.6 on 2023-11-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banco_de_talentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        null=True,
                        verbose_name="Nome da tarefa:",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="trilha",
            name="nome",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                null=True,
                verbose_name="Nome da trilha:",
            ),
        ),
        migrations.CreateModel(
            name="Modulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        null=True,
                        verbose_name="Nome do módulo:",
                    ),
                ),
                (
                    "tarefas",
                    models.ManyToManyField(
                        blank=True,
                        default="",
                        null=True,
                        related_name="modulos",
                        to="banco_de_talentos.tarefa",
                    ),
                ),
            ],
        ),
    ]
