# Generated by Django 4.2.6 on 2023-11-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banco_de_talentos", "0003_trilha_modulos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trilha",
            name="modulos",
            field=models.ManyToManyField(
                blank=True,
                default="",
                null=True,
                related_name="trilhas",
                to="banco_de_talentos.modulo",
            ),
        ),
    ]
