# Generated by Django 4.2.6 on 2023-11-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_de_talentos', '0008_alter_modulo_tarefas'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modulo',
            name='requer_projeto',
            field=models.BooleanField(default=False),
        ),
    ]
