# Generated by Django 4.2.6 on 2023-11-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_de_talentos', '0009_modulo_concluido_modulo_requer_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da tarefa'),
        ),
    ]
