# Generated by Django 4.2.6 on 2023-11-25 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("banco_de_talentos", "0010_tarefa_descricao"),
    ]

    operations = [
        migrations.RemoveField(model_name="modulo", name="tarefas",),
        migrations.AddField(
            model_name="modulo",
            name="tarefas",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarefas",
                to="banco_de_talentos.tarefa",
            ),
            preserve_default=False,
        ),
    ]
