# Generated by Django 4.1.6 on 2023-11-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_de_talentos', '0011_remove_modulo_tarefas_modulo_tarefas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='tarefas',
        ),
        migrations.AddField(
            model_name='modulo',
            name='tarefas',
            field=models.ManyToManyField(blank=True, null=True, related_name='tarefas', to='banco_de_talentos.tarefa'),
        ),
    ]
