# Generated by Django 4.1.6 on 2023-11-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banco_de_talentos", "0014_selo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selo",
            name="selo_bloqueado",
            field=models.FileField(
                blank=True,
                default="",
                null=True,
                upload_to="selos/",
                verbose_name="Imagem do selo bloqueado",
            ),
        ),
        migrations.AlterField(
            model_name="selo",
            name="selo_desbloqueado",
            field=models.FileField(
                blank=True,
                default="",
                null=True,
                upload_to="selos/",
                verbose_name="Imagem do selo desbloqueado",
            ),
        ),
        migrations.AlterField(
            model_name="selo",
            name="selo_normal",
            field=models.FileField(
                blank=True,
                default="",
                null=True,
                upload_to="selos/",
                verbose_name="Imagem do selo",
            ),
        ),
    ]
