# Generated by Django 4.2.6 on 2023-11-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_aluno_matricula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="matricula",
            field=models.ImageField(upload_to=["matriculas"], verbose_name="Matrícula"),
        ),
    ]
