# Generated by Django 4.2.6 on 2023-11-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_alter_aluno_matricula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="matricula",
            field=models.FileField(upload_to="matriculas", verbose_name="Matrícula"),
        ),
    ]
