# Generated by Django 4.2.6 on 2023-11-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_alter_aluno_matricula"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="bio",
            field=models.CharField(
                default="", max_length=150, null=True, verbose_name="Biografia:"
            ),
        ),
    ]
