# Generated by Django 4.2.6 on 2023-11-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0007_alter_aluno_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="bio",
            field=models.CharField(
                blank=True,
                default="",
                max_length=150,
                null=True,
                verbose_name="Biografia:",
            ),
        ),
    ]
