# Generated by Django 4.2.6 on 2023-11-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0010_alter_aluno_discord_alter_aluno_whatsapp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="bio",
            field=models.TextField(
                blank=True,
                default="",
                max_length=150,
                null=True,
                verbose_name="Biografia:",
            ),
        ),
    ]
