# Generated by Django 4.2.6 on 2023-11-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banco_de_talentos", "0005_trilha_imagem_alter_modulo_tarefas_and_more"),
        ("usuarios", "0013_remove_aluno_trilha_aluno_trilhas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="trilhas",
            field=models.ManyToManyField(
                blank=True,
                default="",
                related_name="alunos",
                to="banco_de_talentos.trilha",
            ),
        ),
    ]
