# Generated by Django 4.2.6 on 2023-11-16 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("banco_de_talentos", "0007_alter_trilha_imagem"),
        ("usuarios", "0014_alter_aluno_trilhas"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="trilha_atual",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alunos_em_andamento",
                to="banco_de_talentos.trilha",
            ),
        ),
    ]
