# Generated by Django 4.2.6 on 2023-11-22 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banco_de_talentos', '0009_modulo_concluido_modulo_requer_projeto'),
        ('usuarios', '0018_conclusaotarefa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco_de_talentos.modulo')),
            ],
        ),
    ]
