# Generated by Django 4.2.6 on 2023-11-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='url_projeto',
            field=models.URLField(blank=True, null=True),
        ),
    ]
