# Generated by Django 4.2.6 on 2023-11-23 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banco_de_talentos', '0010_tarefa_descricao'),
        ('usuarios', '0021_alter_projeto_aluno_alter_projeto_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='modulo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banco_de_talentos.modulo'),
        ),
    ]
