# Generated by Django 4.2.6 on 2023-11-23 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0024_alter_projeto_modulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usuarios.aluno"
            ),
        ),
    ]
