# Generated by Django 4.2.6 on 2023-11-23 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("banco_de_talentos", "0010_tarefa_descricao"),
        ("usuarios", "0025_alter_projeto_aluno"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuloAluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url_projeto", models.URLField(blank=True, null=True)),
                (
                    "concluido",
                    models.BooleanField(default=False, verbose_name="Módulo Concluído"),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="usuarios.aluno"
                    ),
                ),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="banco_de_talentos.modulo",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Projeto",),
    ]
