# Generated by Django 4.1.6 on 2023-11-29 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("banco_de_talentos", "0015_alter_selo_selo_bloqueado_and_more"),
        ("usuarios", "0026_moduloaluno_delete_projeto"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeloAluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="usuarios.aluno"
                    ),
                ),
                (
                    "selo",
                    models.ManyToManyField(blank=True, to="banco_de_talentos.selo"),
                ),
            ],
        ),
    ]
