# Generated by Django 4.1.6 on 2023-11-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banco_de_talentos", "0016_modulo_selos"),
        ("usuarios", "0027_seloaluno"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="selos",
            field=models.ManyToManyField(blank=True, to="banco_de_talentos.selo"),
        ),
        migrations.DeleteModel(name="SeloAluno",),
    ]
