# Generated by Django 4.2.6 on 2023-12-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_aluno_selos_delete_seloaluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='perfil_privado',
            field=models.BooleanField(default=False, verbose_name='Perfil privado'),
        ),
    ]
