# Generated by Django 4.2.6 on 2023-12-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0031_aluno_user_delete_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="nivel",
            field=models.IntegerField(default=0, verbose_name="Nível"),
        ),
        migrations.AddField(
            model_name="aluno",
            name="xp",
            field=models.IntegerField(default=0, verbose_name="Pontuação de XP"),
        ),
    ]
