# Generated by Django 4.2.6 on 2023-12-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0033_alter_aluno_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="foto",
            field=models.ImageField(
                default="img/aluno-normal.svg",
                null=True,
                upload_to="perfis",
                verbose_name="Imagem de Perfil: ",
            ),
        ),
    ]
