# Generated by Django 4.2.6 on 2023-12-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0034_alter_aluno_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="foto",
            field=models.ImageField(
                null=True, upload_to="perfis", verbose_name="Imagem de Perfil: "
            ),
        ),
    ]
