# Generated by Django 4.2.6 on 2023-12-11 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("banco_de_talentos", "0016_modulo_selos"),
        ("usuarios", "0036_alter_aluno_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConclusaoTrilha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concluido",
                    models.BooleanField(default=False, verbose_name="Módulo Concluído"),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="usuarios.aluno"
                    ),
                ),
                (
                    "trilha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="banco_de_talentos.trilha",
                    ),
                ),
            ],
        ),
    ]
