# Generated by Django 4.2.6 on 2023-12-20 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("banco_de_talentos", "0016_modulo_selos"),
        ("usuarios", "0037_conclusaotrilha"),
    ]

    operations = [
        migrations.RemoveField(model_name="aluno", name="selos",),
        migrations.AlterField(
            model_name="conclusaotrilha",
            name="concluido",
            field=models.BooleanField(default=False, verbose_name="Trilha concluída"),
        ),
        migrations.CreateModel(
            name="SelosAluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_conquistada", models.DateTimeField(auto_now_add=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="usuarios.aluno"
                    ),
                ),
                (
                    "selo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="banco_de_talentos.selo",
                    ),
                ),
            ],
        ),
    ]
