# Generated by Django 4.2.6 on 2024-01-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0039_rename_aluno_perfil_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conclusaotarefa", options={"verbose_name": "Tarefas Aluno"},
        ),
        migrations.AlterModelOptions(
            name="conclusaotrilha", options={"verbose_name": "Trilhas Aluno"},
        ),
        migrations.AlterModelOptions(
            name="moduloaluno", options={"verbose_name": "Módulos Aluno"},
        ),
        migrations.AlterModelOptions(
            name="perfil", options={"verbose_name": "Perfil"},
        ),
        migrations.AlterModelOptions(
            name="selosaluno", options={"verbose_name": "Selos Aluno"},
        ),
        migrations.AlterField(
            model_name="perfil",
            name="whatsapp",
            field=models.CharField(
                blank=True,
                default="",
                max_length=11,
                null=True,
                verbose_name="Whatsapp:",
            ),
        ),
    ]
